require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
  - bin/**
  - config/**
  - config/**/*
  - cypress/**
  - cypress/**/*
  - db/**
  - lib/**
  - log/**
  - node_modules/**/*
  - public/**
  - storage/**
  - spec/**
  - spec/**/**
  - tmp/**
  - vendor/**
  - vendor/**/*
Documentation:
  Enabled: false
